# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 068e44c09a51337f7497b26109f833967aa8e0d38465d3b831442ba08f14adaf80efa9d642653fc2518eaa7c8852a212a8d58f4d7c72df76e63e4df81cd4e4b0

test:
  secret_key_base: 88f154b038e7e53ea7bdd86449389bdab79fc0bfe6422808e6ee4927e20c5861788374058bdd5e836d754caeca549386f97d405b9778264a8cedbd671615fd4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
