module StocksHelper
  def asi_component_industry(name)
    risk_profile = {
      "Accident & Health Insurance": 1,
      "Advertising Agencies": 1,
      "Aerospace/Defense - Major Diversified": 1,
      "Aerospace/Defense Products & Services": 1,
      "Agricultural Chemicals": 1,
      "Air Delivery & Freight Services": 1,
      "Air Services, Other": 1,
      "Aluminum": 1,
      "Apparel Stores": 1,
      "Appliances": 1,
      "Application Software": 1,
      "Asset Management": 1,
      "Auto Dealerships": 1,
      "Auto Manufacturers - Major": 1,
      "Auto Parts": 1,
      "Auto Parts Stores": 1,
      "Auto Parts Wholesale": 1,
      "Basic Materials Wholesale": 1,
      "Beverages - Brewers": 1,
      "Beverages - Soft Drinks": 1,
      "Beverages - Wineries & Distillers": 1,
      "Biotechnology": 1,
      "Broadcasting - Radio": 1,
      "Broadcasting - TV": 1,
      "Building Materials Wholesale": 1,
      "Business Equipment": 1,
      "Business Services": 1,
      "Business Software & Services": 1,
      "Catalog & Mail Order Houses": 1,
      "CATV Systems": 1,
      "Cement": 1,
      "Chemicals - Major Diversified": 1,
      "Cigarettes": 1,
      "Cleaning Products": 1,
      "Closed-End Fund - Debt": 1,
      "Closed-End Fund - Equity": 1,
      "Closed-End Fund - Foreign": 1,
      "Communication Equipment": 1,
      "Computer Based Systems": 1,
      "Computer Peripherals": 1,
      "Computers Wholesale": 1,
      "Confectioners": 1,
      "Conglomerates": 1,
      "Consumer Services": 1,
      "Copper": 1,
      "Credit Services": 1,
      "Dairy Products": 1,
      "Data Storage Devices": 1,
      "Department Stores": 1,
      "Diagnostic Substances": 1,
      "Discount, Variety Stores": 1,
      "Diversified Communication Services": 1,
      "Diversified Computer Systems": 1,
      "Diversified Electronics": 1,
      "Diversified Investments": 1,
      "Diversified Machinery": 1,
      "Diversified Utilities": 1,
      "Drug Delivery": 1,
      "Drug Manufacturers - Major": 1,
      "Drug Manufacturers - Other": 1,
      "Drug Related Products": 1,
      "Drug Stores": 1,
      "Drugs - Generic": 1,
      "Drugs Wholesale": 1,
      "Education & Training Services": 1,
      "Electric Utilities": 1,
      "Electronic Equipment": 1,
      "Electronics Stores": 1,
      "Electronics Wholesale": 1,
      "Entertainment - Diversified": 1,
      "Exchange Traded Fund": 1,
      "Farm & Construction Machinery": 1,
      "Farm Products": 1,
      "Food - Major Diversified": 1,
      "Food Wholesale": 1,
      "Foreign Regional Banks": 1,
      "Gaming Activities": 1,
      "Gas Utilities": 1,
      "General Building Materials": 1,
      "General Contractors": 1,
      "General Entertainment": 1,
      "Gold": 1,
      "Grocery Stores": 1,
      "Health Care Plans": 1,
      "Healthcare Information Services": 1,
      "Heavy Construction": 1,
      "Home Furnishing Stores": 1,
      "Home Furnishings & Fixtures": 1,
      "Home Health Care": 1,
      "Home Improvement Stores": 1,
      "Hospitals": 1,
      "Housewares & Accessories": 1,
      "Independent Oil & Gas": 1,
      "Industrial Electrical Equipment": 1,
      "Industrial Equipment & Components": 1,
      "Industrial Equipment Wholesale": 1,
      "Industrial Metals & Minerals": 1,
      "Information & Delivery Services": 1,
      "Information Technology Services": 1,
      "Insurance Brokers": 1,
      "Internet Information Providers": 1,
      "Internet Service Providers": 1,
      "Internet Software & Services": 1,
      "Investment Brokerage - National": 1,
      "Investment Brokerage - Regional": 1,
      "Jewelry Stores": 1,
      "Life Insurance": 1,
      "Lodging": 1,
      "Long Distance Carriers": 1,
      "Long-Term Care Facilities": 1,
      "Lumber, Wood Production": 1,
      "Machine Tools & Accessories": 1,
      "Major Airlines": 1,
      "Major Integrated Oil & Gas": 1,
      "Management Services": 1,
      "Manufactured Housing": 1,
      "Marketing Services": 1,
      "Meat Products": 1,
      "Medical Appliances & Equipment": 1,
      "Medical Equipment Wholesale": 1,
      "Medical Instruments & Supplies": 1,
      "Medical Laboratories & Research": 1,
      "Medical Practitioners": 1,
      "Metal Fabrication": 1,
      "Money Center Banks": 1,
      "Mortgage Investment": 1,
      "Movie Production, Theaters": 1,
      "Multimedia & Graphics Software": 1,
      "Music & Video Stores": 1,
      "Networking & Communication Devices": 1,
      "Nonmetallic Mineral Mining": 1,
      "Office Supplies": 1,
      "Oil & Gas Drilling & Exploration": 1,
      "Oil & Gas Equipment & Services": 1,
      "Oil & Gas Pipelines": 1,
      "Oil & Gas Refining & Marketing": 1,
      "Packaging & Containers": 1,
      "Paper & Paper Products": 1,
      "Personal Computers": 1,
      "Personal Products": 1,
      "Personal Services": 1,
      "Photographic Equipment & Supplies": 1,
      "Pollution & Treatment Controls": 1,
      "Printed Circuit Boards": 1,
      "Processed & Packaged Goods": 1,
      "Processing Systems & Products": 1,
      "Property & Casualty Insurance": 1,
      "Property Management": 1,
      "Publishing - Books": 1,
      "Publishing - Newspapers": 1,
      "Publishing - Periodicals": 1,
      "Railroads": 1,
      "Real Estate Development": 1,
      "Recreational Goods, Other": 1,
      "Recreational Vehicles": 1,
      "Regional - Mid-Atlantic Banks": 1,
      "Regional - Midwest Banks": 1,
      "Regional - Northeast Banks": 1,
      "Regional - Pacific Banks": 1,
      "Regional - Southeast Banks": 1,
      "Regional - Southwest  Banks": 1,
      "Regional Airlines": 1,
      "REIT - Diversified": 1,
      "REIT - Healthcare Facilities": 1,
      "REIT - Hotel/Motel": 1,
      "REIT - Industrial": 1,
      "REIT - Office": 1,
      "REIT - Residential": 1,
      "REIT - Retail": 1,
      "Rental & Leasing Services": 1,
      "Research Services": 1,
      "Residential Construction": 1,
      "Resorts & Casinos": 1,
      "Restaurants": 1,
      "Rubber & Plastics": 1,
      "Savings & Loans": 1,
      "Scientific & Technical Instruments": 1,
      "Security & Protection Services": 1,
      "Security Software & Services": 1,
      "Semiconductor - Broad Line": 1,
      "Semiconductor - Integrated Circuits": 1,
      "Semiconductor - Specialized": 1,
      "Semiconductor Equipment & Materials": 1,
      "Semiconductor- Memory Chips": 1,
      "Shipping": 1,
      "Silver": 1,
      "Small Tools & Accessories": 1,
      "Specialized Health Services": 1,
      "Specialty Chemicals": 1,
      "Specialty Eateries": 1,
      "Specialty Retail, Other": 1,
      "Sporting Activities": 1,
      "Sporting Goods": 1,
      "Sporting Goods Stores": 1,
      "Staffing & Outsourcing Services": 1,
      "Steel & Iron": 1,
      "Surety & Title Insurance": 1,
      "Synthetics": 1,
      "Technical & System Software": 1,
      "Technical Services": 1,
      "Telecom Services - Domestic": 1,
      "Telecom Services - Foreign": 1,
      "Textile - Apparel Clothing": 1,
      "Textile - Apparel Footwear & Accessories": 1,
      "Textile Industrial": 1,
      "Tobacco Products, Other": 1,
      "Toy & Hobby Stores": 1,
      "Toys & Games": 1,
      "Trucking": 1,
      "Trucks & Other Vehicles": 1,
      "Waste Management": 1,
      "Water Utilities": 1,
      "Wholesale, Other": 1,
      "Wireless Communications": 1
    }
    return risk_profile[name]
  end
end

