source 'https://rubygems.org'


gem 'rails', '4.2.3'
gem 'pg'
gem 'sass-rails', '~> 5.0'

gem 'jquery-rails'
gem 'httparty'



group :development, :test do
  gem 'byebug'

  gem 'web-console', '~> 2.0'
end

